version: '3.1'

services:

  web:
    image: wordpress
    container_name: wordpressc
    depends_on:
      - db
    ports:
      - "80:80"
    environment:
      - WORDPRESS_DB_HOST=mysqlc
      - WORDPRESS_DB_NAME=wp_database
      - WORDPRESS_DB_USER=wp_user
      - WORDPRESS_DB_PASSWORD=wp_password
    volumes:
      - wordpress-data:/var/www/html
    networks:
      - wordpress-net

  db:
    image: mysql:5.7.28
    container_name: mysqlc
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=wp_database
      - MYSQL_USER=wp_user
      - MYSQL_PASSWORD=wp_password
    volumes:
      - wordpress-mysql-data:/var/lib/mysql
    networks:
      - wordpress-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - PMA_ARBITRARY=1
    networks:
      - wordpress-net

volumes:
  wordpress-data:
      driver: azure_file
      driver_opts:
        share_name: jlopbal-wp
        storage_account_name: jlopbal
  wordpress-mysql-data:
      driver: azure_file
      driver_opts:
        share_name: jlopbal-ms
        storage_account_name: jlopbal

networks: 
  wordpress-net: